/*
 * Datos del prototipo "Carrera de Indias".
 * No contiene lógica: game.js puede leer este catálogo sin dependencias.
 */
(function () {
  "use strict";

  window.CDI_DATA = {
    meta: {
      title: "Real Compañía de la Carrera de Indias",
      version: "0.1.0-prototipo",
      language: "es",
      rulesetMode: "compendio_simultaneo",
      rulesetLabel: "Real Cédula compuesta (1561-1790)",
      allHistoricalReformsActive: true,
      designNote:
        "Las reformas se combinan deliberadamente en un único sistema jugable; no representan una cronología por eras.",
      sourceScope:
        "Capítulos 0-14 de la Real Cédula del proyecto. Las anotaciones del capítulo 15 no se consideran reglas firmes.",
    },

    // Contrato común para que la lógica pueda ignorar de forma segura efectos aún no implementados.
    eventEffectContract: {
      numericStateKeys: [
        "treasury",
        "supplies",
        "morale",
        "cohesion",
        "reputation",
        "information",
        "threat",
        "delayDays",
      ],
      percentageKeys: ["cargoLossPercent"],
      structuredKeys: ["shipDamage", "cargoGain", "flags"],
      rule: "Los números se suman al estado; los porcentajes se limitan a 0-100.",
    },

    config: {
      currency: { id: "reales", singular: "real", plural: "reales", symbol: "r" },
      maxTurns: 12,
      baseEventDrawsPerLeg: 1,
      startingState: {
        treasury: 24000,
        supplies: 70,
        morale: 62,
        cohesion: 65,
        reputation: 50,
        information: 35,
        threat: 28,
        delayDays: 0,
      },
      institutionalHead: {
        administration: "sevilla",
        oceanDispatch: "cadiz",
        explanation:
          "Sevilla conserva la contratación y los registros; Cádiz concentra el despacho marítimo, aunando 1564 y 1717.",
      },
      defaultRates: {
        averiaPerMerchant: 650,
        halfLegAveria: 325,
        royalTributeProfitPercent: 10,
        cargoInsurancePercent: 10,
        hullInsurancePercent: 10,
        basicPortDutyPercent: 5,
      },
      minimumFleet: {
        outbound: { merchant: 1, escortOrAviso: "2 escoltas o 2 avisos" },
        return: { merchant: 1, escortOrAviso: "1 escolta o 2 avisos" },
        everyPrincipalShipNeedsCannons: true,
        flagshipNeedsRepairs: true,
      },
    },

    ports: [
      {
        id: "sevilla",
        name: "Sevilla",
        region: "Andalucía",
        kind: "cabecera_administrativa",
        map: { x: 14, y: 25 },
        functions: ["contratación", "registro", "tesorería", "consulado", "universidad"],
        exports: ["textiles", "herramientas_hierro", "papel_libros", "azogue"],
        imports: ["plata", "cochinilla", "indigo", "cacao"],
        notes: "Nodo administrativo del compendio; la flota oceánica se despacha desde Cádiz.",
      },
      {
        id: "sanlucar",
        name: "Sanlúcar de Barrameda",
        region: "Andalucía",
        kind: "barra_y_revista",
        map: { x: 12, y: 29 },
        functions: ["revista", "aguada", "control_de_calado"],
        exports: ["vino", "aceite_oliva"],
        imports: ["cueros"],
        notes: "Paso de inspección y enlace del Guadalquivir con la bahía gaditana.",
      },
      {
        id: "cadiz",
        name: "Cádiz",
        region: "Andalucía",
        kind: "cabecera_maritima",
        map: { x: 12, y: 32 },
        functions: ["despacho", "registro", "astillero", "mercado", "seguros"],
        exports: ["vino", "aceite_oliva", "ceramica", "textiles"],
        imports: ["plata", "tabaco", "azucar", "cueros"],
        notes: "Cabecera marítima activa conforme a la reforma de 1717 y al proyecto de 1720.",
      },
      {
        id: "canarias",
        name: "Canarias",
        region: "Atlántico oriental",
        kind: "escala_y_aguada",
        map: { x: 20, y: 45 },
        functions: ["aguada", "víveres", "reagrupamiento", "avisos"],
        exports: ["vino", "azucar"],
        imports: [],
        notes: "Última escala habitual antes de tomar los alisios.",
      },
      {
        id: "santo_domingo",
        name: "Santo Domingo",
        region: "Caribe",
        kind: "escala_autorizada",
        map: { x: 64, y: 55 },
        functions: ["aguada", "correo", "agente_de_puerto", "mercado"],
        exports: ["azucar", "cueros", "cacao"],
        imports: ["vino", "textiles", "herramientas_hierro"],
        notes: "Escala opcional y punto de información del Caribe.",
      },
      {
        id: "veracruz",
        name: "Veracruz",
        region: "Nueva España",
        kind: "puerto_de_vuelta",
        map: { x: 55, y: 47 },
        functions: ["feria", "agente_de_puerto", "registro", "reparaciones"],
        exports: ["plata", "cochinilla", "cueros", "vainilla"],
        imports: ["azogue", "textiles", "papel_libros", "vino"],
        notes: "Destino principal de la Flota de Nueva España.",
      },
      {
        id: "cartagena_indias",
        name: "Cartagena de Indias",
        region: "Tierra Firme",
        kind: "puerto_fortificado",
        map: { x: 66, y: 68 },
        functions: ["feria", "fortaleza", "agente_de_puerto", "reparaciones"],
        exports: ["cacao", "indigo", "cueros"],
        imports: ["vino", "textiles", "herramientas_hierro"],
        notes: "Escala fuerte de los Galeones de Tierra Firme.",
      },
      {
        id: "portobelo",
        name: "Portobelo",
        region: "Tierra Firme",
        kind: "puerto_de_feria",
        map: { x: 62, y: 73 },
        functions: ["feria", "tesoro", "agente_de_puerto", "registro"],
        exports: ["plata", "indigo", "cacao"],
        imports: ["azogue", "textiles", "papel_libros", "aceite_oliva"],
        notes: "Terminal de la ruta del istmo y concentración de caudales del Perú.",
      },
      {
        id: "la_habana",
        name: "La Habana",
        region: "Cuba",
        kind: "puerto_de_reunion",
        map: { x: 59, y: 51 },
        functions: ["reunión", "astillero", "aguada", "escolta", "correo"],
        exports: ["tabaco", "azucar", "cueros"],
        imports: ["vino", "aceite_oliva", "ceramica"],
        notes: "Punto de concentración antes del tornaviaje conjunto.",
      },
      {
        id: "azores",
        name: "Azores",
        region: "Atlántico norte",
        kind: "recalada_de_retorno",
        map: { x: 31, y: 30 },
        functions: ["recalada", "avisos", "observación_enemiga", "aguada"],
        exports: ["víveres"],
        imports: [],
        notes: "Referencia del tornaviaje; zona sensible a corsarios y escuadras enemigas.",
      },
    ],

    routes: [
      {
        id: "nueva_espana",
        name: "Flota de Nueva España",
        color: "#c9a451",
        destination: "veracruz",
        summary: "Cádiz–Canarias–Caribe–Veracruz; reunión en La Habana para el retorno.",
        outbound: [
          { id: "ne_i_1", from: "cadiz", to: "canarias", days: 8, risk: 18, distance: 2 },
          { id: "ne_i_2", from: "canarias", to: "santo_domingo", days: 24, risk: 30, distance: 5, optionalStop: true },
          { id: "ne_i_3", from: "santo_domingo", to: "la_habana", days: 7, risk: 36, distance: 2 },
          { id: "ne_i_4", from: "la_habana", to: "veracruz", days: 8, risk: 42, distance: 2 },
        ],
        return: [
          { id: "ne_v_1", from: "veracruz", to: "la_habana", days: 9, risk: 42, distance: 2 },
          { id: "ne_v_2", from: "la_habana", to: "azores", days: 28, risk: 48, distance: 6 },
          { id: "ne_v_3", from: "azores", to: "cadiz", days: 10, risk: 35, distance: 3 },
        ],
        demand: { azogue: 1.28, papel_libros: 1.18, textiles: 1.14, vino: 1.08 },
        returnSupply: { plata: 1.25, cochinilla: 1.35, vainilla: 1.2, cueros: 1.05 },
      },
      {
        id: "tierra_firme",
        name: "Galeones de Tierra Firme",
        color: "#4f8c8d",
        destination: "portobelo",
        summary: "Cádiz–Canarias–Cartagena–Portobelo; regreso por La Habana y Azores.",
        outbound: [
          { id: "tf_i_1", from: "cadiz", to: "canarias", days: 8, risk: 18, distance: 2 },
          { id: "tf_i_2", from: "canarias", to: "cartagena_indias", days: 27, risk: 35, distance: 6 },
          { id: "tf_i_3", from: "cartagena_indias", to: "portobelo", days: 4, risk: 32, distance: 1 },
        ],
        return: [
          { id: "tf_v_1", from: "portobelo", to: "cartagena_indias", days: 4, risk: 34, distance: 1 },
          { id: "tf_v_2", from: "cartagena_indias", to: "la_habana", days: 10, risk: 44, distance: 3 },
          { id: "tf_v_3", from: "la_habana", to: "azores", days: 28, risk: 48, distance: 6 },
          { id: "tf_v_4", from: "azores", to: "cadiz", days: 10, risk: 35, distance: 3 },
        ],
        demand: { textiles: 1.25, herramientas_hierro: 1.18, aceite_oliva: 1.12, papel_libros: 1.1 },
        returnSupply: { plata: 1.32, indigo: 1.28, cacao: 1.2, cueros: 1.08 },
      },
    ],

    goods: [
      { id: "vino", name: "Vino", direction: "ida", category: "consumo", buy: 70, sell: 118, volume: 1, fragility: 18, spoilage: 8, icon: "🍷" },
      { id: "aceite_oliva", name: "Aceite de oliva", direction: "ida", category: "consumo", buy: 62, sell: 108, volume: 1, fragility: 14, spoilage: 5, icon: "🫒" },
      { id: "textiles", name: "Paños y textiles", direction: "ida", category: "manufactura", buy: 115, sell: 205, volume: 1, fragility: 6, spoilage: 0, icon: "🧵" },
      { id: "herramientas_hierro", name: "Hierro y herramientas", direction: "ida", category: "manufactura", buy: 98, sell: 170, volume: 2, fragility: 2, spoilage: 0, icon: "⚒️" },
      { id: "papel_libros", name: "Papel y libros", direction: "ida", category: "manufactura", buy: 105, sell: 186, volume: 1, fragility: 28, spoilage: 0, icon: "📜" },
      { id: "azogue", name: "Azogue", direction: "ida", category: "estrategica", buy: 185, sell: 315, volume: 1, fragility: 10, spoilage: 0, hazardous: true, icon: "⚗️" },
      { id: "ceramica", name: "Cerámica y vidrio", direction: "ida", category: "manufactura", buy: 54, sell: 102, volume: 1, fragility: 42, spoilage: 0, icon: "🏺" },
      { id: "repuestos", name: "Repuestos navales", direction: "ida", category: "pertrecho", buy: 130, sell: 190, volume: 2, fragility: 4, spoilage: 0, icon: "🪵" },
      { id: "plata", name: "Plata registrada", direction: "vuelta", category: "tesoro", buy: 480, sell: 740, volume: 1, fragility: 0, spoilage: 0, threatBonus: 14, icon: "🪙" },
      { id: "cochinilla", name: "Grana cochinilla", direction: "vuelta", category: "tinte", buy: 255, sell: 465, volume: 1, fragility: 8, spoilage: 1, icon: "🔴" },
      { id: "indigo", name: "Añil", direction: "vuelta", category: "tinte", buy: 215, sell: 392, volume: 1, fragility: 5, spoilage: 0, icon: "🔵" },
      { id: "cacao", name: "Cacao", direction: "vuelta", category: "consumo", buy: 155, sell: 286, volume: 1, fragility: 12, spoilage: 14, icon: "🍫" },
      { id: "tabaco", name: "Tabaco", direction: "vuelta", category: "consumo", buy: 132, sell: 242, volume: 1, fragility: 16, spoilage: 5, icon: "🍂" },
      { id: "azucar", name: "Azúcar", direction: "vuelta", category: "consumo", buy: 86, sell: 151, volume: 2, fragility: 10, spoilage: 4, icon: "◻️" },
      { id: "cueros", name: "Cueros", direction: "vuelta", category: "materia_prima", buy: 72, sell: 132, volume: 2, fragility: 3, spoilage: 3, icon: "🐂" },
      { id: "palo_tinte", name: "Palo de tinte", direction: "vuelta", category: "tinte", buy: 58, sell: 116, volume: 3, fragility: 0, spoilage: 0, icon: "🪵" },
      { id: "vainilla", name: "Vainilla", direction: "vuelta", category: "lujo", buy: 175, sell: 338, volume: 1, fragility: 9, spoilage: 10, icon: "🌿" },
    ],

    ships: [
      { id: "nao_mercante", name: "Nao mercante", role: "merchant", eraTag: "tradicional", cost: 4700, capacity: 12, hull: 82, sails: 68, speed: 4, cannons: 8, crew: 42, upkeep: 180, repairCapacity: 5, insuranceValue: 4200 },
      { id: "galeon_mercante", name: "Galeón mercante", role: "merchant", eraTag: "convoy", cost: 7100, capacity: 11, hull: 104, sails: 72, speed: 4, cannons: 18, crew: 70, upkeep: 280, repairCapacity: 8, insuranceValue: 6500 },
      { id: "urca", name: "Urca", role: "merchant", eraTag: "carga", cost: 5700, capacity: 17, hull: 92, sails: 60, speed: 3, cannons: 6, crew: 46, upkeep: 220, repairCapacity: 6, insuranceValue: 5200 },
      { id: "indiaman", name: "Indiamán", role: "merchant", eraTag: "reforma", cost: 6600, capacity: 14, hull: 96, sails: 74, speed: 4, cannons: 14, crew: 62, upkeep: 250, repairCapacity: 7, insuranceValue: 6000 },
      { id: "galeon_guerra", name: "Galeón de guerra", role: "escort", eraTag: "convoy", cost: 9800, capacity: 3, hull: 118, sails: 70, speed: 4, cannons: 36, crew: 145, upkeep: 480, repairCapacity: 12, insuranceValue: 8800 },
      { id: "fragata_escolta", name: "Fragata de escolta", role: "escort", eraTag: "reforma", cost: 8200, capacity: 2, hull: 82, sails: 92, speed: 6, cannons: 26, crew: 112, upkeep: 410, repairCapacity: 9, insuranceValue: 7400 },
      { id: "navio_linea", name: "Navío de línea", role: "escort", eraTag: "borbonico", cost: 14800, capacity: 2, hull: 145, sails: 78, speed: 3, cannons: 64, crew: 360, upkeep: 720, repairCapacity: 16, insuranceValue: 13200 },
      { id: "patache", name: "Patache de aviso", role: "aviso", eraTag: "tradicional", cost: 3200, capacity: 2, hull: 54, sails: 94, speed: 7, cannons: 6, crew: 28, upkeep: 120, repairCapacity: 3, insuranceValue: 2800 },
      { id: "bergantin_correo", name: "Bergantín correo", role: "aviso", eraTag: "correo_1764", cost: 4100, capacity: 2, hull: 60, sails: 105, speed: 8, cannons: 8, crew: 38, upkeep: 155, repairCapacity: 3, insuranceValue: 3600 },
      { id: "balandra_aviso", name: "Balandra de aviso", role: "aviso", eraTag: "reforma", cost: 3600, capacity: 1, hull: 48, sails: 112, speed: 9, cannons: 4, crew: 24, upkeep: 135, repairCapacity: 2, insuranceValue: 3100 },
    ],

    fleetTemplates: [
      {
        id: "flota_equilibrada",
        name: "Flota equilibrada",
        ships: ["galeon_mercante", "nao_mercante", "urca", "galeon_guerra", "fragata_escolta", "patache"],
        formation: "capitana delante, mercantes al centro, almiranta a retaguardia, escolta a barlovento",
      },
      {
        id: "flota_avisos",
        name: "Convoy ligero con avisos",
        ships: ["nao_mercante", "indiaman", "urca", "patache", "bergantin_correo"],
        formation: "dos avisos exploran; los mercantes permanecen en formación cerrada",
      },
    ],

    events: [
      {
        id: "alisios_favorables",
        title: "Alisios favorables",
        category: "meteorologia",
        weight: 8,
        when: { phases: ["ida"], routeIds: ["nueva_espana", "tierra_firme"] },
        conditionText: "En mar abierto durante el viaje de ida.",
        description: "El viento constante hincha las velas y permite conservar agua y bizcocho.",
        choices: [
          { id: "aprovechar", label: "Mantener todo el aparejo", result: "La flota gana varios días sin romper la formación.", effects: { delayDays: -3, supplies: 5, morale: 3 } },
          { id: "prudencia", label: "Navegar con prudencia", result: "La ventaja es menor, pero los palos sufren menos.", effects: { delayDays: -1, cohesion: 3 } },
        ],
      },
      {
        id: "calma_chicha",
        title: "Calma chicha",
        category: "meteorologia",
        weight: 7,
        when: { phases: ["ida", "tornaviaje"], routeIds: ["nueva_espana", "tierra_firme"] },
        conditionText: "Cualquier travesía oceánica.",
        description: "El mar parece aceite y la flota consume víveres sin avanzar.",
        choices: [
          { id: "esperar", label: "Racionar y esperar", result: "La disciplina evita el pánico, pero la demora es seria.", effects: { delayDays: 4, supplies: -8, morale: -2 } },
          { id: "remolcar", label: "Remolcar los rezagados", result: "Se conserva la formación a costa de esfuerzo y jarcia.", effects: { delayDays: 2, supplies: -5, cohesion: 4, shipDamage: { target: "random_escort", sails: -4 } } },
        ],
      },
      {
        id: "temporal_atlantico",
        title: "Temporal del Atlántico",
        category: "meteorologia",
        weight: 8,
        when: { phases: ["ida", "tornaviaje"], routeIds: ["nueva_espana", "tierra_firme"] },
        conditionText: "En los tramos Cádiz–Canarias o Azores–Cádiz.",
        description: "Un frente violento obliga a escoger entre conservar rumbo o ponerse a la capa.",
        choices: [
          { id: "capa", label: "Ponerse a la capa", result: "La flota aguanta unida, aunque llega tarde.", effects: { delayDays: 3, cohesion: 2, shipDamage: { target: "random_ship", hull: -5, sails: -6 } } },
          { id: "forzar", label: "Forzar la marcha", result: "Se gana tiempo, pero un barco recibe una avería severa.", effects: { delayDays: 1, morale: -3, shipDamage: { target: "random_merchant", hull: -12, sails: -10 } } },
        ],
      },
      {
        id: "huracan_caribe",
        title: "Huracán en el Caribe",
        category: "meteorologia",
        weight: 4,
        when: { phases: ["ida", "tornaviaje"], routeIds: ["nueva_espana", "tierra_firme"], minThreat: 20 },
        conditionText: "Entre Santo Domingo, La Habana, Veracruz y Cartagena.",
        description: "El cielo se cierra con rapidez. La carga, los palos y la cohesión quedan amenazados.",
        choices: [
          { id: "refugio", label: "Buscar abrigo", result: "La recalada salva carga, pero altera el calendario.", effects: { delayDays: 6, supplies: -6, cohesion: -2, shipDamage: { target: "random_ship", hull: -7, sails: -8 } } },
          { id: "capear", label: "Capear juntos", result: "La formación resiste con daños y pérdida de mercancía.", effects: { delayDays: 3, cargoLossPercent: 12, morale: -6, shipDamage: { target: "all_ships", hull: -8, sails: -9 } } },
        ],
      },
      {
        id: "bajos_bahamas",
        title: "Bajos de las Bahamas",
        category: "navegacion",
        weight: 5,
        when: { phases: ["tornaviaje"], routeIds: ["nueva_espana", "tierra_firme"], requiresAnyRole: ["aviso"] },
        conditionText: "Al salir del canal de la Florida; un aviso reduce el riesgo.",
        description: "Sondas inciertas y corrientes cruzadas amenazan al mercante de mayor calado.",
        choices: [
          { id: "sondar", label: "Enviar el aviso a sondar", result: "El convoy encuentra paso seguro.", effects: { delayDays: 1, information: 5, cohesion: 2 } },
          { id: "atajo", label: "Seguir el derrotero corto", result: "Se ahorra tiempo, pero el mercante roza el fondo.", effects: { delayDays: -1, shipDamage: { target: "largest_merchant", hull: -13 }, cargoLossPercent: 4 } },
        ],
      },
      {
        id: "corriente_golfo",
        title: "La corriente del Golfo",
        category: "navegacion",
        weight: 7,
        when: { phases: ["tornaviaje"], routeIds: ["nueva_espana", "tierra_firme"] },
        conditionText: "Después de la reunión en La Habana.",
        description: "El piloto mayor reconoce el flujo que llevará la flota hacia el nordeste.",
        choices: [
          { id: "seguir", label: "Seguir la corriente", result: "El tornaviaje se acelera y mejora la moral.", effects: { delayDays: -4, morale: 4, information: 2 } },
          { id: "ruta_baja", label: "Mantener latitud conservadora", result: "Menor ganancia de tiempo, mayor cohesión.", effects: { delayDays: -1, cohesion: 4 } },
        ],
      },
      {
        id: "agua_corrompida",
        title: "Agua corrompida",
        category: "salud",
        weight: 6,
        when: { phases: ["ida", "tornaviaje"], minDelayDays: 3 },
        conditionText: "La flota acumula retraso o ha evitado una aguada.",
        description: "Varios toneles huelen mal y crece la inquietud entre las tripulaciones.",
        choices: [
          { id: "racionar", label: "Racionar los toneles sanos", result: "La flota sigue, con sed y disciplina.", effects: { supplies: -9, morale: -6, delayDays: 1 } },
          { id: "aguada", label: "Desviarse a una aguada", result: "El agua se repone, pero la ruta queda más expuesta.", effects: { supplies: 14, delayDays: 4, threat: 5 } },
        ],
      },
      {
        id: "escorbuto",
        title: "Escorbuto a bordo",
        category: "salud",
        weight: 5,
        when: { phases: ["ida", "tornaviaje"], minDelayDays: 5 },
        conditionText: "Travesía prolongada con reservas reducidas.",
        description: "Las encías sangran y faltan brazos para las maniobras.",
        choices: [
          { id: "repartir", label: "Abrir las reservas frescas", result: "Los enfermos mejoran y la moral se estabiliza.", effects: { supplies: -12, morale: 3, delayDays: 1 } },
          { id: "mantener", label: "Mantener la ración", result: "Se preservan víveres, pero cae el rendimiento.", effects: { morale: -9, delayDays: 3, cohesion: -3 } },
        ],
      },
      {
        id: "fiebre_tropical",
        title: "Fiebres tras la recalada",
        category: "salud",
        weight: 5,
        when: { phases: ["ida", "tornaviaje"], portRegions: ["Caribe", "Tierra Firme", "Nueva España"] },
        conditionText: "Después de tocar un puerto americano.",
        description: "Marineros de varios barcos caen enfermos y se discute si esperar.",
        choices: [
          { id: "hospital", label: "Esperar a los convalecientes", result: "La demora preserva vidas y reputación.", effects: { delayDays: 4, morale: 2, reputation: 3, supplies: -5 } },
          { id: "zarpar", label: "Zarpar con dotaciones reducidas", result: "Se cumple el calendario a costa de moral y maniobra.", effects: { morale: -7, cohesion: -4, shipDamage: { target: "random_ship", sails: -4 } } },
        ],
      },
      {
        id: "mastil_quebrado",
        title: "Mástil quebrado",
        category: "averia",
        weight: 6,
        when: { phases: ["ida", "tornaviaje"], requiresAnyRole: ["merchant"] },
        conditionText: "Un mercante sufre fatiga de aparejo.",
        description: "Un crujido seco deja al rezagado sin el mastelero de gavia.",
        choices: [
          { id: "reparar", label: "Consumir reparaciones comunes", result: "La avería se atiende conforme a los privilegios de avería.", effects: { supplies: -4, delayDays: 2, cohesion: 4, shipDamage: { target: "random_merchant", sails: -3 } } },
          { id: "remolcar", label: "Remolcar hasta puerto", result: "Se conservan pertrechos, pero toda la flota pierde tiempo.", effects: { delayDays: 4, morale: -2, cohesion: 2 } },
        ],
      },
      {
        id: "via_de_agua",
        title: "Vía de agua",
        category: "averia",
        weight: 6,
        when: { phases: ["ida", "tornaviaje"], requiresAnyRole: ["merchant"] },
        conditionText: "Cualquier mercante con daño previo o mar gruesa.",
        description: "Las bombas apenas contienen la entrada de agua en una bodega cargada.",
        choices: [
          { id: "carena_mar", label: "Reparar en la mar", result: "Carpinteros y escoltas prestan ayuda.", effects: { delayDays: 2, supplies: -6, shipDamage: { target: "damaged_merchant", hull: -5 }, reputation: 2 } },
          { id: "alijar", label: "Alijar la bodega", result: "El barco recupera flotabilidad perdiendo parte de la carga.", effects: { cargoLossPercent: 10, cohesion: -2, shipDamage: { target: "damaged_merchant", hull: -2 } } },
        ],
      },
      {
        id: "incendio_bodega",
        title: "Incendio en la bodega",
        category: "averia",
        weight: 3,
        when: { phases: ["ida", "tornaviaje"], requiresAnyRole: ["merchant"] },
        conditionText: "Riesgo mayor con azogue, aceite o pertrechos.",
        description: "Una lámpara cae durante el relevo nocturno y el humo invade la cubierta baja.",
        choices: [
          { id: "inundar", label: "Inundar el compartimento", result: "Se salva el barco sacrificando mercancía.", effects: { cargoLossPercent: 16, morale: -3, shipDamage: { target: "random_merchant", hull: -4 } } },
          { id: "brigada", label: "Enviar brigadas de la escolta", result: "La cooperación limita el fuego, aunque causa demora.", effects: { delayDays: 2, cohesion: 5, shipDamage: { target: "random_merchant", hull: -8 }, supplies: -3 } },
        ],
      },
      {
        id: "averia_gruesa",
        title: "Avería gruesa",
        category: "institucional",
        weight: 4,
        when: { phases: ["ida", "tornaviaje"], requiresAnyRole: ["merchant"] },
        conditionText: "Peligro común que exige un sacrificio deliberado.",
        description: "Para salvar la flota hay que cortar aparejo y echar carga al mar; el Escribano debe registrarlo.",
        choices: [
          { id: "sacrificio_comun", label: "Declarar sacrificio común", result: "La pérdida queda asentada para su reparto posterior.", effects: { cargoLossPercent: 8, cohesion: 7, reputation: 4, flags: ["reclamacion_averia_gruesa"] } },
          { id: "cada_barco", label: "Que cada capitán responda", result: "Se conserva el tesoro común, pero se resiente la compañía.", effects: { cargoLossPercent: 5, cohesion: -10, reputation: -4 } },
        ],
      },
      {
        id: "velas_desconocidas",
        title: "Velas desconocidas",
        category: "amenaza",
        weight: 8,
        when: { phases: ["ida", "tornaviaje"] },
        conditionText: "Amenaza mayor sin avisos o con poca información.",
        description: "El vigía distingue velas a sotavento, pero aún no puede reconocer pabellón.",
        choices: [
          { id: "aviso", label: "Enviar un aviso", result: "La exploración aclara la situación sin romper el convoy.", effects: { information: 8, threat: -3, delayDays: 1 } },
          { id: "cerrar", label: "Cerrar formación", result: "Los mercantes quedan cubiertos, aunque todos pierden velocidad.", effects: { cohesion: 6, threat: -2, delayDays: 2 } },
          { id: "ignorar", label: "Mantener rumbo", result: "Se evita la demora, pero aumenta la incertidumbre.", effects: { threat: 8, morale: -3 } },
        ],
      },
      {
        id: "ataque_corsario",
        title: "Ataque corsario",
        category: "combate",
        weight: 6,
        when: { phases: ["ida", "tornaviaje"], minThreat: 32 },
        conditionText: "Probable con amenaza alta; la escolta reduce sus consecuencias.",
        description: "Dos corsarios intentan cortar al último mercante de la línea.",
        choices: [
          { id: "escolta", label: "Ordenar a la escolta interceptar", result: "La maniobra protege el mercante a costa de munición y daños.", effects: { threat: -7, morale: 5, reputation: 4, shipDamage: { target: "random_escort", hull: -9, sails: -5 }, supplies: -3 } },
          { id: "huir", label: "Soltar vela y evitar combate", result: "Parte del convoy escapa, pero se pierde cohesión y carga.", effects: { cohesion: -12, cargoLossPercent: 6, threat: 3, morale: -5 } },
        ],
      },
      {
        id: "escuadra_enemiga",
        title: "Escuadra enemiga en la derrota",
        category: "combate",
        weight: 3,
        when: { phases: ["ida", "tornaviaje"], minThreat: 45 },
        conditionText: "Amenaza muy alta o aproximación a un puerto bloqueado.",
        description: "Una fuerza superior guarda la ruta directa y obliga al Capitán General a decidir.",
        choices: [
          { id: "desviar", label: "Desviar la flota", result: "Se evita la batalla, pero se consumen víveres y calendario.", effects: { delayDays: 5, supplies: -10, threat: -8, information: 3 } },
          { id: "romper", label: "Romper el bloqueo", result: "La escolta abre paso con alto coste.", effects: { threat: -12, reputation: 8, morale: 4, shipDamage: { target: "all_escorts", hull: -15, sails: -8 }, cargoLossPercent: 5 } },
        ],
      },
      {
        id: "mercante_rezagado",
        title: "Mercante rezagado",
        category: "disciplina",
        weight: 7,
        when: { phases: ["ida", "tornaviaje"], maxCohesion: 70, requiresAnyRole: ["merchant"] },
        conditionText: "Cohesión imperfecta o barco con daños.",
        description: "La Almiranta señala que un mercante pierde contacto al caer la tarde.",
        choices: [
          { id: "esperar", label: "Esperar y auxiliar", result: "La protección común se cumple y mejora la confianza.", effects: { delayDays: 2, cohesion: 7, reputation: 4, supplies: -3 } },
          { id: "seguir", label: "Mantener la derrota", result: "El convoy no se detiene; el rezagado queda expuesto.", effects: { cohesion: -9, reputation: -6, threat: 6, flags: ["mercante_sin_cobertura"] } },
        ],
      },
      {
        id: "conserva_solicita_amparo",
        title: "Navegación en conserva",
        category: "institucional",
        weight: 5,
        when: { phases: ["ida", "tornaviaje"] },
        conditionText: "Un navío español no inscrito se aproxima al convoy.",
        description: "Su capitán pide navegar cerca, aunque no ha pagado avería ni goza de sus privilegios.",
        choices: [
          { id: "permitir", label: "Permitir la conserva", result: "Se le deja acompañar sin asumir formalmente su protección.", effects: { reputation: 3, cohesion: -2, threat: 2 } },
          { id: "inscribir", label: "Admitirlo tras cobrar media avería", result: "El Escribano registra el pago y la escolta asume su defensa.", effects: { treasury: 325, cohesion: 4, reputation: 2, flags: ["navio_incorporado"] } },
        ],
      },
      {
        id: "registro_intercepta",
        title: "Navío de registro",
        category: "institucional",
        weight: 4,
        when: { phases: ["ida", "tornaviaje"] },
        conditionText: "Régimen de permisos de 1741 activo junto al convoy.",
        description: "Un navío con licencia particular aporta noticias y solicita intercambio de repuestos.",
        choices: [
          { id: "cooperar", label: "Intercambiar información y repuestos", result: "Ambas expediciones quedan mejor informadas.", effects: { treasury: -120, supplies: 5, information: 9, reputation: 3 } },
          { id: "reservar", label: "Proteger los secretos de ruta", result: "Se conserva el material, pero se pierde una fuente de noticias.", effects: { information: -2, cohesion: 2 } },
        ],
      },
      {
        id: "aviso_correo",
        title: "Aviso del correo marítimo",
        category: "informacion",
        weight: 6,
        when: { phases: ["ida", "tornaviaje"], requiresAnyRole: ["aviso"] },
        conditionText: "La red de correos de 1764 está activa.",
        description: "Un bergantín trae precios, estado de puertos y movimientos enemigos.",
        choices: [
          { id: "mercado", label: "Priorizar noticias de mercado", result: "Los agentes podrán vender con mejor criterio.", effects: { information: 12, treasury: 180, flags: ["mercado_conocido"] } },
          { id: "militar", label: "Priorizar noticias de guerra", result: "La derrota se ajusta para reducir encuentros.", effects: { information: 8, threat: -10, delayDays: 1 } },
        ],
      },
      {
        id: "contrabando_propuesto",
        title: "Propuesta de contrabando",
        category: "dilema",
        weight: 4,
        when: { phases: ["ida", "tornaviaje"], minInformation: 20 },
        conditionText: "Un intermediario conoce una cala fuera del registro.",
        description: "Ofrece ocultar parte de la carga y eludir derechos a cambio de una comisión.",
        choices: [
          { id: "rechazar", label: "Rechazar y dejar constancia", result: "El Escribano preserva la legalidad y la reputación.", effects: { reputation: 7, cohesion: 3, treasury: -80 } },
          { id: "aceptar", label: "Aceptar el trato", result: "La ganancia es inmediata, pero queda riesgo de causa ante la Audiencia.", effects: { treasury: 900, reputation: -10, threat: 7, flags: ["expediente_contrabando"] } },
        ],
      },
      {
        id: "disputa_mando",
        title: "Disputa entre Capitana y Almiranta",
        category: "disciplina",
        weight: 5,
        when: { phases: ["ida", "tornaviaje"], maxCohesion: 60 },
        conditionText: "Cohesión baja y cambio de rumbo discutido.",
        description: "El Almirante considera demasiado arriesgada la señal del Capitán General.",
        choices: [
          { id: "consejo", label: "Convocar consejo breve", result: "Se asienta la decisión en el diario de la flota.", effects: { delayDays: 1, cohesion: 7, reputation: 2 } },
          { id: "obediencia", label: "Imponer la orden de la Capitana", result: "La maniobra es inmediata, pero deja resentimiento.", effects: { cohesion: -7, morale: -3, delayDays: -1 } },
        ],
      },
      {
        id: "presa_enemiga",
        title: "Presa enemiga abandonada",
        category: "oportunidad",
        weight: 3,
        when: { phases: ["ida", "tornaviaje"], requiresAnyRole: ["escort"] },
        conditionText: "La escolta encuentra un navío enemigo maltrecho.",
        description: "Puede capturarse, socorrerse a sus supervivientes o dejarlo atrás.",
        choices: [
          { id: "capturar", label: "Tomar la presa", result: "La escolta dispone de la captura y el Escribano la registra.", effects: { treasury: 1100, delayDays: 2, threat: 4, reputation: 2, flags: ["presa_capturada"] } },
          { id: "socorrer", label: "Socorrer y desarmar", result: "La compañía gana fama de conducta honorable.", effects: { supplies: -5, delayDays: 1, reputation: 8, morale: 3 } },
        ],
      },
      {
        id: "recalada_habana",
        title: "Recalada extraordinaria en La Habana",
        category: "logistica",
        weight: 5,
        when: { phases: ["tornaviaje"], routeIds: ["nueva_espana", "tierra_firme"] },
        conditionText: "Antes de cruzar el Atlántico de vuelta.",
        description: "El astillero puede reparar y reunir navíos, pero la estación avanza.",
        choices: [
          { id: "carena", label: "Carena y reparación general", result: "La flota parte tarde, sólida y cohesionada.", effects: { treasury: -700, delayDays: 4, cohesion: 8, morale: 5, shipDamage: { target: "all_ships", hull: 8, sails: 8 } } },
          { id: "aguada", label: "Solo agua y víveres", result: "La escala es breve y repone lo imprescindible.", effects: { treasury: -220, supplies: 18, delayDays: 1 } },
        ],
      },
    ],

    // Todas estas capas históricas están activas a la vez por decisión de diseño.
    historicalFrameworks: [
      {
        id: "reforma_1561_1564",
        years: [1561, 1564],
        name: "Convoyes y Ordenanzas de la Casa de la Contratación",
        active: true,
        contributions: ["flotas organizadas", "Capitana y Almiranta", "registro", "artillería y revista", "pilotos y escribanos"],
        gameplay: "Fija el esqueleto naval, el despacho obligatorio y la prueba documental.",
      },
      {
        id: "reforma_1717_1720",
        years: [1717, 1720],
        name: "Cabecera gaditana y Proyecto para Galeones y Flotas",
        active: true,
        contributions: ["despacho en Cádiz", "calendario y composición", "fiscalidad ordenada", "avisos y registros"],
        gameplay: "Cádiz es la cabecera marítima y cada expedición debe superar una fase formal de preparación.",
      },
      {
        id: "reforma_1741",
        years: [1741],
        name: "Consolidación de los navíos de registro",
        active: true,
        contributions: ["licencias particulares", "navíos sueltos autorizados", "rutas complementarias"],
        gameplay: "Los registros coexisten con la flota y pueden aportar información, carga o escolta sin idénticos privilegios.",
      },
      {
        id: "reforma_1764_1765",
        years: [1764, 1765],
        name: "Correo marítimo y apertura antillana",
        active: true,
        contributions: ["bergantines correo", "información más rápida", "nuevos puertos autorizados", "agentes de puerto"],
        gameplay: "Los avisos mejoran inteligencia y mercado; ciertas escalas caribeñas quedan habilitadas.",
      },
      {
        id: "reforma_1778_1790",
        years: [1778, 1790],
        name: "Comercio autorizado ampliado y continuidad tras la Casa",
        active: true,
        contributions: ["red de puertos habilitados", "comercio directo regulado", "aduanas", "traspaso institucional al Consulado"],
        gameplay: "Se amplían mercados sin eliminar registros, tributos, seguros ni autoridad corporativa.",
      },
    ],

    regulations: [
      {
        id: "norma_compendio",
        title: "Vigencia simultánea del compendio",
        kind: "meta_regla",
        chapterRefs: [14],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720", "reforma_1741", "reforma_1764_1765", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Ninguna reforma sustituye a otra: cada una aporta su mecánica compatible al reglamento común.",
        gameplay: "Convoy, registros, correo, puertos ampliados y Consulado funcionan en la misma campaña.",
      },
      {
        id: "norma_navios_sueltos",
        title: "Navíos sueltos, registros y asientos",
        kind: "navegacion",
        chapterRefs: [0],
        reformLinks: ["reforma_1741", "reforma_1764_1765", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Un navío fuera de la flota puede operar mediante licencia, registro o asiento, pero no recibe automáticamente avería, seguro ni protección.",
        gameplay: "Ruta individual de mayor libertad y riesgo; puede colaborar con el convoy mediante acuerdos expresos.",
      },
      {
        id: "norma_inscripcion_despacho",
        title: "Inscripción y despacho",
        kind: "obligacion",
        chapterRefs: [1],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "Todo capitán que pretenda la protección de la flota debe inscribir barcos, carga y tramo antes de zarpar.",
        gameplay: "La pantalla de despacho cierra manifiestos y crea el asiento probatorio del Escribano.",
      },
      {
        id: "norma_revista_mareantes",
        title: "Revista de barcos y pilotos",
        kind: "seguridad",
        chapterRefs: [1, 9],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "La Universidad de Mareantes puede aprobar, aplazar o negar la salida por falta de capacidad, cañones, reparaciones o seguridad.",
        gameplay: "Una flota que no supera mínimos no puede zarpar o renuncia a privilegios.",
      },
      {
        id: "norma_averia",
        title: "Tasa de avería",
        kind: "fiscal_y_proteccion",
        chapterRefs: [2, 4],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "Cada mercante inscrito paga avería fija por la ida, la vuelta o ambas; financia escolta, auxilios, reparaciones y navíos prestados.",
        gameplay: "650 reales por expedición completa o 325 por un solo tramo; admite devolución y exenciones registradas.",
      },
      {
        id: "norma_privilegios_averia",
        title: "Privilegios y límites de la avería",
        kind: "proteccion",
        chapterRefs: [2, 7, 11],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "La cobertura rige del amarre de salida al de regreso; impago, dolo o salida de mínimos pueden suspenderla.",
        gameplay: "Activa auxilio y reclamaciones únicamente cuando el registro demuestra buena fe y vigencia.",
      },
      {
        id: "norma_tributo_real",
        title: "Tributo Real de carga y porte",
        kind: "fiscal",
        chapterRefs: [3, 10, 13],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Quien recibe carga de Cargadores paga su coste más una parte del beneficio; a falta de cálculo se aplica un 10%. El Cargador Particular no paga por su propia carga.",
        gameplay: "Remunera recopilación y transporte, alimenta la tesorería y diferencia carga común de privada.",
      },
      {
        id: "norma_escolta",
        title: "Servicio de escolta",
        kind: "naval",
        chapterRefs: [4, 6, 7],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "La escolta navega preferentemente a barlovento, protege mercantes y puede cobrar en moneda, carga, reparaciones o exención futura.",
        gameplay: "Los escoltas no llevan mercantes personales; pueden variar entre ida y vuelta y deciden el destino de presas legítimas.",
      },
      {
        id: "norma_seguro",
        title: "Seguro marítimo facultativo",
        kind: "seguro",
        chapterRefs: [5, 8, 11],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Barcos propios y mercancías registradas pueden asegurarse antes del tramo; el siniestro debe ser fortuito y sin falta de diligencia.",
        gameplay: "Prima ordinaria del 10%; la póliza se aplica a todos los barcos personales elegibles, no solo al más valioso.",
      },
      {
        id: "norma_orden_ida",
        title: "Orden de navegación de ida",
        kind: "naval",
        chapterRefs: [6],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "La Capitana abre la formación, la Almiranta la cierra, los mercantes quedan en el cuerpo y avisos/escolta exploran y socorren.",
        gameplay: "La ida exige dos escoltas o, en su defecto, dos avisos para conservar privilegios.",
      },
      {
        id: "norma_conserva_asiento_beneficencia",
        title: "Conserva, asiento y beneficencia",
        kind: "incorporacion",
        chapterRefs: [0, 6],
        reformLinks: ["reforma_1741", "reforma_1764_1765", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "La conserva no concede privilegios; el navío de asiento extranjero paga doble avería o recibe gracia; la beneficencia exige mayoría simple.",
        gameplay: "Permite incorporar barcos a mitad de expedición con estatutos y costes diferentes.",
      },
      {
        id: "norma_tornaviaje",
        title: "Mínimos y sucesión en el tornaviaje",
        kind: "naval",
        chapterRefs: [7],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720"],
        activeByDefault: true,
        rule: "El regreso requiere una escolta o dos avisos; si falta el Capitán General, el Almirante asume el mando y se nombra sustituto cuando proceda.",
        gameplay: "Zarpar sin mínimos anula avería y seguros del retorno; un nuevo mercante puede entrar pagando media tasa.",
      },
      {
        id: "norma_registro_1741",
        title: "Coexistencia de flota y navíos de registro",
        kind: "licencia",
        chapterRefs: [0, 6, 7],
        reformLinks: ["reforma_1741"],
        activeByDefault: true,
        rule: "El registro autorizado puede navegar fuera del convoy, intercambiar noticias y contratar protección sin convertir la flota en obligatoria para toda operación.",
        gameplay: "Genera eventos de información, refuerzo o competencia comercial.",
      },
      {
        id: "norma_correo_1764",
        title: "Correo marítimo y barcos de aviso",
        kind: "informacion",
        chapterRefs: [6, 7, 9, 10],
        reformLinks: ["reforma_1764_1765"],
        activeByDefault: true,
        rule: "Los avisos y bergantines correo adelantan noticias de mercado, guerra, puertos y derroteros.",
        gameplay: "Mejoran información, permiten explorar y pueden satisfacer mínimos navales cuando la Cédula lo admite.",
      },
      {
        id: "norma_puertos_ampliados",
        title: "Red ampliada de puertos autorizados",
        kind: "comercio",
        chapterRefs: [0, 3, 6, 10],
        reformLinks: ["reforma_1764_1765", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "La apertura de puertos permite escalas y comercio directo regulado, sin abolir licencias, registros, tributos ni secreto operativo.",
        gameplay: "Aumenta destinos y mercados; cada escala añade oportunidades, demora y exposición.",
      },
      {
        id: "norma_participaciones",
        title: "Participaciones de expedición",
        kind: "financiacion",
        chapterRefs: [8, 13],
        reformLinks: ["reforma_1717_1720", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Los partícipes financian riesgo asegurado y responden a prorrata; pueden transmitir participaciones sin recibir secretos de ruta.",
        gameplay: "El valor sube con excedentes y baja con indemnizaciones; admite testaferro extranjero sin revelar el itinerario.",
      },
      {
        id: "norma_universidad",
        title: "Universidad de Mareantes",
        kind: "institucion",
        chapterRefs: [1, 5, 9],
        reformLinks: ["reforma_1561_1564"],
        activeByDefault: true,
        rule: "Forma pilotos, revisa capacidad y carga, comparte derroteros y certifica pruebas para seguros.",
        gameplay: "Su Director, Piloto Mayor y Escribano habilitan mejoras de navegación y reducen fraude.",
      },
      {
        id: "norma_consulado",
        title: "Consulado de Mercaderes",
        kind: "institucion",
        chapterRefs: [2, 3, 4, 5, 10, 13],
        reformLinks: ["reforma_1561_1564", "reforma_1717_1720", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Compra y reparte carga, organiza escolta, cobra tasas y seguros, conserva secretos y administra la tesorería.",
        gameplay: "El Tesorero centraliza cuentas; Cargadores y Mercaderes preparan mercado y despacho.",
      },
      {
        id: "norma_continuidad_1790",
        title: "Continuidad institucional tras 1790",
        kind: "institucion",
        chapterRefs: [10, 11, 14],
        reformLinks: ["reforma_1778_1790"],
        activeByDefault: true,
        rule: "Al suprimirse la Casa, sus funciones jugables necesarias de registro, cuentas y justicia continúan en Consulado, Universidad y Real Audiencia.",
        gameplay: "Evita eliminar sistemas previos y justifica el compendio simultáneo.",
      },
      {
        id: "norma_audiencia",
        title: "Real Audiencia mercantil",
        kind: "justicia",
        chapterRefs: [11],
        reformLinks: ["reforma_1561_1564", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "Prior y dos Cónsules resuelven reclamaciones con manifiestos, testigos y revisores; quien participó en la flota litigiosa debe abstenerse.",
        gameplay: "Las decisiones se revisan por el Prior y después por el Consulado; fraude y dolo excluyen indemnización.",
      },
      {
        id: "norma_miembros_secreto",
        title: "Ingreso, reputación y secreto",
        kind: "corporativa",
        chapterRefs: [12],
        reformLinks: ["reforma_1561_1564", "reforma_1741", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "El ingreso ordinario exige propuesta, buena fama, compromiso de secreto y mayoría absoluta; un aliado extranjero requiere dos tercios.",
        gameplay: "Reputación e información son recursos; filtrar rutas puede provocar expulsión y amenaza.",
      },
      {
        id: "norma_financiacion",
        title: "Financiación sin deuda pública",
        kind: "financiacion",
        chapterRefs: [8, 13],
        reformLinks: ["reforma_1717_1720", "reforma_1778_1790"],
        activeByDefault: true,
        rule: "La compañía usa avería, tributo, excedente de seguros, donaciones, presas, cuotas, préstamos particulares y participaciones; no emite bonos públicos.",
        gameplay: "Cada fuente tiene coste o riesgo, y la tesorería común debe seguir solvente tras indemnizaciones.",
      },
      {
        id: "norma_reforma_interna",
        title: "Modificación y derogación",
        kind: "gobierno",
        chapterRefs: [14],
        reformLinks: ["reforma_1778_1790"],
        activeByDefault: true,
        rule: "Añadir o modificar exige mayoría absoluta; derogar exige dos tercios de todos los miembros.",
        gameplay: "En campaña permite ajustar parámetros sin desactivar automáticamente las capas históricas.",
      },
    ],

    chapters: [
      { number: 0, title: "Régimen de navíos sueltos", summary: "Licencias, registros, asientos y límites de privilegios fuera del convoy.", regulationIds: ["norma_navios_sueltos", "norma_conserva_asiento_beneficencia", "norma_registro_1741", "norma_puertos_ampliados"] },
      { number: 1, title: "Preparación o despacho", summary: "Inscripción, manifiesto, mandos, pertrechos y aprobación de salida.", regulationIds: ["norma_inscripcion_despacho", "norma_revista_mareantes"] },
      { number: 2, title: "Tasa de avería", summary: "Pago común, tramos, beneficios, exenciones y devoluciones.", regulationIds: ["norma_averia", "norma_privilegios_averia", "norma_consulado"] },
      { number: 3, title: "Tributo Real", summary: "Retribución de carga y transporte, con tipo supletorio del diez por ciento.", regulationIds: ["norma_tributo_real", "norma_puertos_ampliados", "norma_consulado"] },
      { number: 4, title: "La escolta", summary: "Servicio naval, posición a barlovento, paga, diligencia y presas.", regulationIds: ["norma_averia", "norma_escolta", "norma_consulado"] },
      { number: 5, title: "Seguros marítimos", summary: "Pólizas de barco y mercancía, registro, prima y buena fe.", regulationIds: ["norma_seguro", "norma_universidad", "norma_consulado"] },
      { number: 6, title: "Viaje de ida", summary: "Composición, formación, mínimos, conserva, agentes y avisos.", regulationIds: ["norma_escolta", "norma_orden_ida", "norma_conserva_asiento_beneficencia", "norma_registro_1741", "norma_correo_1764", "norma_puertos_ampliados"] },
      { number: 7, title: "Tornaviaje", summary: "Reunión, mínimos, sucesión del mando y nuevas incorporaciones.", regulationIds: ["norma_privilegios_averia", "norma_escolta", "norma_tornaviaje", "norma_registro_1741", "norma_correo_1764"] },
      { number: 8, title: "Participaciones", summary: "Capital de riesgo, prorrateo, transmisión y secreto de ruta.", regulationIds: ["norma_seguro", "norma_participaciones", "norma_financiacion"] },
      { number: 9, title: "Universidad de Mareantes", summary: "Formación, revisión, derroteros y asistencia mutua.", regulationIds: ["norma_revista_mareantes", "norma_correo_1764", "norma_universidad"] },
      { number: 10, title: "Consulado de Mercaderes", summary: "Carga, tasas, escolta, tesorería, mercado y gobierno mercantil.", regulationIds: ["norma_tributo_real", "norma_correo_1764", "norma_puertos_ampliados", "norma_consulado", "norma_continuidad_1790"] },
      { number: 11, title: "Real Audiencia", summary: "Prueba, reclamaciones, abstención, revisión y fraude.", regulationIds: ["norma_privilegios_averia", "norma_seguro", "norma_continuidad_1790", "norma_audiencia"] },
      { number: 12, title: "Miembros de la Compañía", summary: "Ingreso, cargos, deberes, secretos y pérdida de la condición.", regulationIds: ["norma_miembros_secreto"] },
      { number: 13, title: "Financiación", summary: "Ingresos corporativos, participaciones y préstamos particulares limitados.", regulationIds: ["norma_tributo_real", "norma_participaciones", "norma_consulado", "norma_financiacion"] },
      { number: 14, title: "Reforma de la Real Cédula", summary: "Mayorías para modificar, añadir o derogar normas.", regulationIds: ["norma_compendio", "norma_continuidad_1790", "norma_reforma_interna"] },
    ],

    glossary: [
      { term: "Avería", definition: "Contribución común que financia protección y auxilios de la flota; no equivale al seguro facultativo." },
      { term: "Capitana", definition: "Nave que abre la formación y porta al Capitán General." },
      { term: "Almiranta", definition: "Nave que cierra la formación y porta al Almirante, segundo en el mando." },
      { term: "Aviso", definition: "Barco ligero de exploración y mensajería; desde 1764 se integra también en la red de correo marítimo." },
      { term: "Cargador", definition: "Persona o agente que recopila, registra y entrega mercancías para la expedición." },
      { term: "Conserva", definition: "Navegación próxima al convoy sin inscripción ni igualdad automática de privilegios." },
      { term: "Navío de registro", definition: "Buque con licencia particular que opera al margen del convoy regular, pero bajo control documental y fiscal." },
      { term: "Tornaviaje", definition: "Viaje de regreso a la Península, normalmente concentrado en La Habana y dirigido hacia Azores y Cádiz." },
    ],
  };
})();
